---
- name: "get artifact"
  copy: 
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz

- name: extract backend files
  become: true
  shell: |
    cd /home/ubuntu
    tar xzf artifact.tar.gz -C .
- name: "open the server"
  shell: | 
    pm2 stop default
    pm2 start npm -- start
